site_name: Arjun Ramesh
nav:
  - Home: index.md
  - Professional Experience: experience.md
  - Projects: projects.md

  - Hobbies: hobbies.md
  #- Miscellaneous: misc.md
  - CV: cv.md

theme:
  name: material
  custom_dir: overrides

  logo: assets/home/favicon.ico
  favicon: assets/home/hacker.ico
  palette:
    scheme: default # custom_scheme # default
    primary: blue-grey
  font:
    text: EB-Garamond
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    #- navigation.top
    #- navigation.indexes
    - toc.integrate

    - header.autohide

extra_css:
  - stylesheets/extra.css


extra:
  social:
    - icon: fontawesome/brands/github #material/github
      link: https://github.com/arjunr2
      name: GitHub

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ajramesh
      name: LinkedIn

    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCQLPzl1LHeF25W3SiKSAqGQ?view_as=subscriber
      name: Youtube

    - icon: material/gmail
      link: mailto:arjunr2@andrew.cmu.edu
      name: Email me!

  #generator: false


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright_notice:
  author: Arjun Ramesh
  update_time: true

